import { NextRequest, NextResponse } from "next/server";
import { Resend } from "resend";

const resend = new Resend(process.env.RESEND_API_KEY);

/**
 * API Route: Send email alert for dangerous events
 *
 * POST /api/send-email
 *
 * Request body:
 * {
 *   eventDescription: string,
 *   timestamp: string,
 *   frameImage: string (base64 JPEG)
 * }
 */
export async function POST(request: NextRequest) {
  try {
    // Check if Resend API key is configured
    if (!process.env.RESEND_API_KEY) {
      console.warn("⚠️ RESEND_API_KEY not configured, skipping email");
      return NextResponse.json(
        { success: false, error: "Email service not configured" },
        { status: 503 }
      );
    }

    // Parse request body
    const body = await request.json();
    const { eventDescription, timestamp, frameImage } = body;

    // Validate required fields
    if (!eventDescription || !timestamp) {
      return NextResponse.json(
        { success: false, error: "Missing required fields" },
        { status: 400 }
      );
    }

    // Get email configuration from environment
    const fromEmail = process.env.ALERT_EMAIL_FROM || "alerts@vigilanteai.dev";
    const toEmail = process.env.ALERT_EMAIL_TO || "security@vigilanteai.dev";

    // Prepare email content
    const emailSubject = `🚨 Security Alert: ${eventDescription}`;
    const emailHtml = `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="utf-8">
        <style>
          body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
            line-height: 1.6;
            color: #333;
            max-width: 600px;
            margin: 0 auto;
            padding: 20px;
          }
          .header {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 30px;
            border-radius: 10px 10px 0 0;
            text-align: center;
          }
          .content {
            background: #f8f9fa;
            padding: 30px;
            border: 1px solid #dee2e6;
            border-top: none;
            border-radius: 0 0 10px 10px;
          }
          .alert-box {
            background: #fff3cd;
            border-left: 4px solid #ffc107;
            padding: 15px;
            margin: 20px 0;
          }
          .danger-box {
            background: #f8d7da;
            border-left: 4px solid #dc3545;
            padding: 15px;
            margin: 20px 0;
          }
          .timestamp {
            color: #6c757d;
            font-size: 14px;
          }
          .footer {
            text-align: center;
            margin-top: 30px;
            padding-top: 20px;
            border-top: 1px solid #dee2e6;
            color: #6c757d;
            font-size: 12px;
          }
          img {
            max-width: 100%;
            height: auto;
            border-radius: 8px;
            margin: 20px 0;
          }
        </style>
      </head>
      <body>
        <div class="header">
          <h1>🚨 VigilanteAI Security Alert</h1>
        </div>
        <div class="content">
          <div class="danger-box">
            <h2 style="margin-top: 0; color: #dc3545;">⚠️ Dangerous Event Detected</h2>
            <p><strong>${eventDescription}</strong></p>
          </div>

          <div class="alert-box">
            <p class="timestamp">
              <strong>Timestamp:</strong> ${timestamp}<br>
              <strong>Detection Method:</strong> Phase 2 VLM Analysis (Google Gemini)
            </p>
          </div>

          ${frameImage ? `
            <h3>Captured Frame:</h3>
            <img src="data:image/jpeg;base64,${frameImage}" alt="Security camera frame" />
          ` : ''}

          <p style="margin-top: 30px;">
            This alert was automatically generated by VigilanteAI's real-time surveillance system.
            Please review the situation immediately and take appropriate action.
          </p>
        </div>
        <div class="footer">
          <p>
            Powered by VigilanteAI | Phase 2: VLM Analysis<br>
            This is an automated alert. Do not reply to this email.
          </p>
        </div>
      </body>
      </html>
    `;

    // Send email via Resend
    console.log(`📧 Sending email alert to ${toEmail}...`);
    const data = await resend.emails.send({
      from: fromEmail,
      to: toEmail,
      subject: emailSubject,
      html: emailHtml,
    });

    console.log("✅ Email sent successfully:", data);

    return NextResponse.json({
      success: true,
      messageId: data.id,
    });
  } catch (error: any) {
    console.error("❌ Email send error:", error);

    // Provide user-friendly error messages
    let errorMessage = "Failed to send email";
    if (error?.message?.includes("API key")) {
      errorMessage = "Invalid Resend API key";
    } else if (error?.message?.includes("quota")) {
      errorMessage = "Email quota exceeded";
    } else if (error?.message) {
      errorMessage = error.message;
    }

    return NextResponse.json(
      { success: false, error: errorMessage },
      { status: 500 }
    );
  }
}

// Health check endpoint
export async function GET() {
  const isConfigured = !!process.env.RESEND_API_KEY;

  return NextResponse.json({
    service: "VigilanteAI Email Alerts",
    configured: isConfigured,
    status: isConfigured ? "ready" : "not configured",
  });
}
